import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import AdBannerSlot from "@/components/ads/AdBannerSlot";
import { getAvailableAds } from "@/lib/services/ads";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ads = await getAvailableAds();

  const ad =
    ads.length > 0
      ? ads[Math.floor(Math.random() * ads.length)]
      : null;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {ad && (
          <AdBannerSlot
            ad={{
              id: ad.id,
              image: ad.image,
              target_url: ad.target_url,
            }}
          />
        )}

        {children}

      </body>
    </html>
  );
}